stages:
  - build

variables:
  FROM_IMAGE_TAG: $CI_COMMIT_REF_NAME
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

.build: &build-template
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --build-arg FROM_IMAGE_TAG=$FROM_IMAGE_TAG --destination $IMAGE_TAG

build-latest:
  <<: *build-template
  variables:
    FROM_IMAGE_TAG: latest
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  only:
    - master

build-tagged:
  <<: *build-template
  only:
    - tags
